plugins {
    id 'com.android.application'
    id 'org.mozilla.rust-android-gradle.rust-android'
}

android {
    namespace 'com.vuzt'
    compileSdk 34

    defaultConfig {
        applicationId "com.vuzt"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    // KITA HAPUS ndkVersion DI SINI AGAR TIDAK BENTROK

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
}

cargo {
    module  = "../rust"
    libname = "pemanasan_jni"
    targets = ["arm64"]
    profile = "release"
}

tasks.whenTaskAdded { task ->
    if ((task.name == 'javaPreCompileDebug' || task.name == 'javaPreCompileRelease')) {
        task.dependsOn 'cargoBuild'
    }
}
