plugins {
    id 'com.android.application'
    id 'org.mozilla.rust-android-gradle.rust-android'
}

android {
    namespace 'com.vuzt'
    compileSdk 34

    defaultConfig {
        applicationId "com.vuzt"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
}

cargo {
    module  = "../rust"       // Lokasi Cargo.toml
    libname = "pemanasan_jni" // Harus sama dengan [lib] name di Cargo.toml
    targets = ["arm64"]       // Kita fokus ke ARM64 dulu agar cepat
    profile = "release"       // Biar hasil Rust-nya kencang
}

// Otomatis jalankan cargoBuild sebelum compile Java
tasks.whenTaskAdded { task ->
    if ((task.name == 'javaPreCompileDebug' || task.name == 'javaPreCompileRelease')) {
        task.dependsOn 'cargoBuild'
    }
}

dependencies {
    // Tidak butuh dependensi tambahan untuk Rust
}
